import type { DemoAdminFixtures, DemoAdminSnapshot } from './types';

const products = [
  {
    id: 'product-armchair-01',
    name: 'Кресло Forma',
    category: 'Кресла',
    rooms: ['Гостиная', 'Спальня'],
    skuCount: 2,
    priceFrom: 45900,
    totalStock: 10,
    mediaCount: 8,
    turntable: 'ready',
  },
  {
    id: 'product-bed-02',
    name: 'Кровать Noma',
    category: 'Кровати',
    rooms: ['Спальня'],
    skuCount: 2,
    priceFrom: 78900,
    totalStock: 5,
    mediaCount: 6,
    turntable: 'partial',
  },
  {
    id: 'product-console-03',
    name: 'Консоль Linea',
    category: 'Консоли',
    rooms: ['Прихожая', 'Гостиная'],
    skuCount: 1,
    priceFrom: 34900,
    totalStock: 11,
    mediaCount: 4,
    turntable: 'none',
  },
  {
    id: 'product-lamp-04',
    name: 'Лампа Lumen',
    category: 'Освещение',
    rooms: ['Спальня', 'Кабинет'],
    skuCount: 1,
    priceFrom: 18900,
    totalStock: 18,
    mediaCount: 3,
    turntable: 'none',
  },
  {
    id: 'product-sofa-05',
    name: 'Диван Tact',
    category: 'Диваны',
    rooms: ['Гостиная'],
    skuCount: 2,
    priceFrom: 112900,
    totalStock: 4,
    mediaCount: 9,
    turntable: 'ready',
  },
  {
    id: 'product-table-06',
    name: 'Стол Axis',
    category: 'Столы',
    rooms: ['Кухня', 'Столовая'],
    skuCount: 1,
    priceFrom: 62900,
    totalStock: 9,
    mediaCount: 5,
    turntable: 'none',
  },
] as const;

const skus = [
  {
    id: 'sku-armchair-01-sand',
    productId: 'product-armchair-01',
    articleNumber: 'EVN-ARM-001-S',
    combinationLabel: 'Песочный · Рогожка',
    selections: ['color-sand', 'material-fabric'],
    price: 45900,
    oldPrice: 49900,
    stock: 7,
    active: true,
    mediaCount: 4,
    turntable: 'ready',
  },
  {
    id: 'sku-armchair-01-graphite',
    productId: 'product-armchair-01',
    articleNumber: 'EVN-ARM-001-G',
    combinationLabel: 'Графит · Велюр',
    selections: ['color-graphite', 'material-velvet'],
    price: 48900,
    oldPrice: null,
    stock: 3,
    active: true,
    mediaCount: 4,
    turntable: 'ready',
  },
  {
    id: 'sku-bed-02-sand',
    productId: 'product-bed-02',
    articleNumber: 'EVN-BED-002-S',
    combinationLabel: 'Песочный · Велюр',
    selections: ['color-sand', 'material-velvet'],
    price: 78900,
    oldPrice: 84900,
    stock: 2,
    active: true,
    mediaCount: 3,
    turntable: 'partial',
  },
  {
    id: 'sku-bed-02-graphite',
    productId: 'product-bed-02',
    articleNumber: 'EVN-BED-002-G',
    combinationLabel: 'Графит · Велюр',
    selections: ['color-graphite', 'material-velvet'],
    price: 82900,
    oldPrice: null,
    stock: 3,
    active: true,
    mediaCount: 3,
    turntable: 'partial',
  },
  {
    id: 'sku-console-03-olive',
    productId: 'product-console-03',
    articleNumber: 'EVN-CON-003-O',
    combinationLabel: 'Оливковый · Шпон дуба',
    selections: ['color-olive', 'material-wood'],
    price: 34900,
    oldPrice: null,
    stock: 11,
    active: true,
    mediaCount: 4,
    turntable: 'none',
  },
  {
    id: 'sku-lamp-04-sand',
    productId: 'product-lamp-04',
    articleNumber: 'EVN-LMP-004-S',
    combinationLabel: 'Песочный · Шпон дуба',
    selections: ['color-sand', 'material-wood'],
    price: 18900,
    oldPrice: null,
    stock: 18,
    active: true,
    mediaCount: 3,
    turntable: 'none',
  },
  {
    id: 'sku-sofa-05-sand',
    productId: 'product-sofa-05',
    articleNumber: 'EVN-SOF-005-S',
    combinationLabel: 'Песочный · Рогожка',
    selections: ['color-sand', 'material-fabric'],
    price: 112900,
    oldPrice: 119900,
    stock: 1,
    active: true,
    mediaCount: 5,
    turntable: 'ready',
  },
  {
    id: 'sku-sofa-05-graphite',
    productId: 'product-sofa-05',
    articleNumber: 'EVN-SOF-005-G',
    combinationLabel: 'Графит · Велюр',
    selections: ['color-graphite', 'material-velvet'],
    price: 118900,
    oldPrice: null,
    stock: 3,
    active: true,
    mediaCount: 4,
    turntable: 'ready',
  },
  {
    id: 'sku-table-06-olive',
    productId: 'product-table-06',
    articleNumber: 'EVN-TBL-006-O',
    combinationLabel: 'Оливковый · Шпон дуба',
    selections: ['color-olive', 'material-wood'],
    price: 62900,
    oldPrice: null,
    stock: 9,
    active: true,
    mediaCount: 5,
    turntable: 'none',
  },
] as const;

const orders = [
  {
    id: 'order-1048',
    number: 'EVN-1048',
    customerName: 'Алина Морозова',
    status: 'PROCESSING',
    paymentLabel: 'Оплачено',
    totalAmount: 158800,
    createdLabel: '26 августа 2026, 11:24',
    lines: [
      { productName: 'Диван Tact', articleNumber: 'EVN-SOF-005-S', quantity: 1, unitPrice: 112900, lineTotal: 112900 },
      { productName: 'Лампа Lumen', articleNumber: 'EVN-LMP-004-S', quantity: 1, unitPrice: 18900, lineTotal: 18900 },
    ],
  },
  {
    id: 'order-1047',
    number: 'EVN-1047',
    customerName: 'Максим Орлов',
    status: 'SHIPPED',
    paymentLabel: 'Оплачено',
    totalAmount: 82900,
    createdLabel: '26 августа 2026, 09:16',
    lines: [
      { productName: 'Кровать Noma', articleNumber: 'EVN-BED-002-G', quantity: 1, unitPrice: 82900, lineTotal: 82900 },
    ],
  },
  {
    id: 'order-1046',
    number: 'EVN-1046',
    customerName: 'София Белова',
    status: 'DELIVERED',
    paymentLabel: 'Оплачено',
    totalAmount: 97800,
    createdLabel: '25 августа 2026, 18:42',
    lines: [
      { productName: 'Стол Axis', articleNumber: 'EVN-TBL-006-O', quantity: 1, unitPrice: 62900, lineTotal: 62900 },
      { productName: 'Лампа Lumen', articleNumber: 'EVN-LMP-004-S', quantity: 1, unitPrice: 18900, lineTotal: 18900 },
    ],
  },
  {
    id: 'order-1045',
    number: 'EVN-1045',
    customerName: 'Алина Морозова',
    status: 'PENDING',
    paymentLabel: 'Ожидает оплаты',
    totalAmount: 48900,
    createdLabel: '25 августа 2026, 15:08',
    lines: [
      { productName: 'Кресло Forma', articleNumber: 'EVN-ARM-001-G', quantity: 1, unitPrice: 48900, lineTotal: 48900 },
    ],
  },
  {
    id: 'order-1044',
    number: 'EVN-1044',
    customerName: 'Максим Орлов',
    status: 'CANCELLED',
    paymentLabel: 'Не оплачено',
    totalAmount: 34900,
    createdLabel: '24 августа 2026, 13:31',
    lines: [
      { productName: 'Консоль Linea', articleNumber: 'EVN-CON-003-O', quantity: 1, unitPrice: 34900, lineTotal: 34900 },
    ],
  },
  {
    id: 'order-1043',
    number: 'EVN-1043',
    customerName: 'София Белова',
    status: 'DELIVERED',
    paymentLabel: 'Оплачено',
    totalAmount: 45900,
    createdLabel: '23 августа 2026, 17:04',
    lines: [
      { productName: 'Кресло Forma', articleNumber: 'EVN-ARM-001-S', quantity: 1, unitPrice: 45900, lineTotal: 45900 },
    ],
  },
  {
    id: 'order-1042',
    number: 'EVN-1042',
    customerName: 'Илья Волков',
    status: 'PROCESSING',
    paymentLabel: 'Оплачено',
    totalAmount: 62900,
    createdLabel: '22 августа 2026, 12:18',
    lines: [
      { productName: 'Стол Axis', articleNumber: 'EVN-TBL-006-O', quantity: 1, unitPrice: 62900, lineTotal: 62900 },
    ],
  },
  {
    id: 'order-1041',
    number: 'EVN-1041',
    customerName: 'Илья Волков',
    status: 'SHIPPED',
    paymentLabel: 'Оплачено',
    totalAmount: 18900,
    createdLabel: '21 августа 2026, 10:02',
    lines: [
      { productName: 'Лампа Lumen', articleNumber: 'EVN-LMP-004-S', quantity: 1, unitPrice: 18900, lineTotal: 18900 },
    ],
  },
] as const;

export const demoAdminFixtures: Readonly<DemoAdminFixtures> = {
  dashboard: {
    kpis: [
      { id: 'revenue', label: 'Выручка за период', value: '486 320 ₽', detail: '+12% к прошлому периоду' },
      { id: 'orders', label: 'Заказы', value: '64', detail: '8 синтетических примеров' },
      { id: 'average-order', label: 'Средний чек', value: '7 599 ₽', detail: 'по завершённым заказам' },
      { id: 'low-stock', label: 'Мало остатков', value: '3 SKU', detail: 'остаток до 3 единиц' },
      { id: 'products', label: 'Товары', value: '6', detail: 'из 6 опубликованы' },
      { id: 'turntables', label: '360° обзор', value: '3 товара', detail: 'готовы или частично готовы' },
    ],
    revenue: [
      { label: '20 авг', value: 48200 },
      { label: '21 авг', value: 63100 },
      { label: '22 авг', value: 57400 },
      { label: '23 авг', value: 79900 },
      { label: '24 авг', value: 88620 },
      { label: '25 авг', value: 91200 },
      { label: '26 авг', value: 57800 },
    ],
    statuses: [
      { status: 'PENDING', label: 'Новые', value: 1 },
      { status: 'PROCESSING', label: 'В работе', value: 2 },
      { status: 'SHIPPED', label: 'В доставке', value: 2 },
      { status: 'DELIVERED', label: 'Доставлены', value: 2 },
      { status: 'CANCELLED', label: 'Отменены', value: 1 },
    ],
  },
  catalog: {
    products,
    options: [
      {
        id: 'option-color',
        name: 'Цвет',
        values: [
          { id: 'color-sand', label: 'Песочный' },
          { id: 'color-graphite', label: 'Графит' },
          { id: 'color-olive', label: 'Оливковый' },
        ],
        usedByProducts: 6,
      },
      {
        id: 'option-material',
        name: 'Материал',
        values: [
          { id: 'material-fabric', label: 'Рогожка' },
          { id: 'material-velvet', label: 'Велюр' },
          { id: 'material-wood', label: 'Шпон дуба' },
        ],
        usedByProducts: 6,
      },
    ],
    skus,
  },
  orders,
  customers: [
    {
      id: 'customer-01',
      name: 'Алина Морозова',
      email: 'alina@evironn.invalid',
      role: 'CUSTOMER',
      orderCount: 3,
      totalSpent: 207700,
      registeredLabel: '12 июня 2026',
    },
    {
      id: 'customer-02',
      name: 'Максим Орлов',
      email: 'maxim@evironn.invalid',
      role: 'CUSTOMER',
      orderCount: 2,
      totalSpent: 117800,
      registeredLabel: '21 июня 2026',
    },
    {
      id: 'customer-03',
      name: 'София Белова',
      email: 'sofia@evironn.invalid',
      role: 'CUSTOMER',
      orderCount: 2,
      totalSpent: 143700,
      registeredLabel: '2 июля 2026',
    },
    {
      id: 'customer-04',
      name: 'Илья Волков',
      email: 'ilya@evironn.invalid',
      role: 'ADMIN',
      orderCount: 2,
      totalSpent: 81800,
      registeredLabel: '8 июля 2026',
    },
  ],
  coupons: [
    { id: 'coupon-01', code: 'FORMA10', type: 'PERCENT', value: 10, windowLabel: 'Без срока', active: true },
    { id: 'coupon-02', code: 'WELCOME15', type: 'PERCENT', value: 15, windowLabel: 'До 31 декабря 2026', active: true },
    { id: 'coupon-03', code: 'ROOM20', type: 'PERCENT', value: 20, windowLabel: 'До 30 сентября 2026', active: false },
  ],
};

export function getDemoAdminSnapshot(): Readonly<DemoAdminSnapshot> {
  const { catalog, dashboard, orders, customers, coupons } = demoAdminFixtures;
  const firstSkuByProduct = new Map<string, (typeof catalog.skus)[number]>();
  for (const sku of catalog.skus) if (!firstSkuByProduct.has(sku.productId)) firstSkuByProduct.set(sku.productId, sku);

  return {
    generatedLabel: 'Демонстрационный срез · 26 августа 2026',
    kpis: { revenue: 486320, orders: 64, averageOrder: 7599, conversion: 3.8 },
    revenueSeries: dashboard.revenue.map(({ label, value }) => ({ label, revenue: value })),
    products: catalog.products.map((product) => ({
      id: product.id,
      name: product.name,
      sku: firstSkuByProduct.get(product.id)?.articleNumber ?? '',
      category: product.category,
      price: product.priceFrom,
      stock: product.totalStock,
      active: product.totalStock > 0,
    })),
    orders: orders.map((order, index) => ({
      id: order.id,
      number: order.number,
      customerId: customers[index % customers.length].id,
      customerName: order.customerName,
      status: order.status,
      totalAmount: order.totalAmount,
      createdLabel: order.createdLabel,
    })),
    customers,
    coupons: coupons.map((coupon) => ({
      id: coupon.id,
      code: coupon.code,
      percent: coupon.value,
      active: coupon.active,
      expiresLabel: coupon.windowLabel,
    })),
  };
}
